name: h5pay
description: A new flutter plugin project.
version: 0.0.1
author: nekocode <nekocode.cn@gmail.com>
homepage:

flutter:
  plugin:
    androidPackage: cn.nekocode.h5pay
    pluginClass: H5payPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

